# Generated by Django 5.2.7 on 2025-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('func_path', models.CharField(max_length=255, verbose_name='函数路径')),
                ('trigger_type', models.CharField(choices=[('cron', 'Cron'), ('interval', 'Interval'), ('date', 'Once')], default='cron', max_length=20, verbose_name='触发类型')),
                ('cron_second', models.CharField(blank=True, default='0', max_length=64)),
                ('cron_minute', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_hour', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_day', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_month', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_day_of_week', models.CharField(blank=True, default='*', max_length=64)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('once_run_at', models.DateTimeField(blank=True, null=True)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('job_id', models.CharField(blank=True, default='', editable=False, max_length=128)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
            },
        ),
    ]
