"""
Django settings for django_vue_adminx project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
backend_apps = BASE_DIR / 'apps'
if str(backend_apps) not in sys.path:
    sys.path.insert(0, str(backend_apps))
# 环境变量（用于 Docker）
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--mpclg7e91pkc&c+dz3lcf%=ddfye@9asvaf4z7xnjd9tpt#bb')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 已在文件顶部定义

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG 已在文件顶部定义

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI服务器，需要放在最前面
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'apps.codegen',
    'apps.tasks.apps.TasksConfig',
    'apps.rbac.apps.RbacConfig',
    'apps.curdexample.apps.CurdexampleConfig',
    'apps.audit.apps.AuditConfig',
    'apps.shop.apps.ShopConfig',
    'apps.chat.apps.ChatConfig',
    'apps.system.apps.SystemConfig',
    'apps.office.apps.OfficeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'apps.audit.middleware.OperationLogMiddleware',  # 操作日志中间件
]

ROOT_URLCONF = 'django_vue_adminx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_vue_adminx.wsgi.application'
ASGI_APPLICATION = 'django_vue_adminx.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 支持从环境变量读取数据库配置（用于 Docker）
if os.getenv('DATABASE_URL'):
    # 使用 MySQL（Docker 环境）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'django_vue_adminx'),
            'USER': os.getenv('DB_USER', 'django'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'django123'),
            'HOST': os.getenv('DB_HOST', 'db'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    # 使用 SQLite（开发环境）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS 配置：允许跨域请求
CORS_ORIGIN_ALLOW_ALL = True  # 如果设置为True，则允许所有源进行跨域访问
CORS_ALLOW_CREDENTIALS = True  # 允许携带 Cookie（Session 认证需要）

# CSRF 配置：允许来自前端的 CSRF 请求
# 注意：CSRF_TRUSTED_ORIGINS 需要包含协议和端口号
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# CSRF Cookie 设置（跨域时需要）
CSRF_COOKIE_SAMESITE = 'Lax'  # 开发环境使用 Lax（生产环境跨域时使用 None）
CSRF_COOKIE_SECURE = False  # 开发环境使用 False（生产环境应使用 True）
CSRF_COOKIE_HTTPONLY = False  # 允许 JavaScript 读取 Cookie
CSRF_USE_SESSIONS = False  # 使用 Cookie 而不是 Session
CORS_ALLOW_METHODS = (
     'DELETE',
     'GET',
     'OPTIONS',
     'PATCH',
     'POST',
     'PUT',
)
CORS_ALLOW_HEADERS = (
     'accept-encoding',
     'authorization',
     'content-type',
     'dnt',
     'origin',
     'user-agent',
     'x-csrftoken',
     'x-requested-with',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# DRF 基础配置：默认登录可访问，提供分页、过滤、搜索、排序后端
# 使用 RBAC 权限控制作为全局默认权限类
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.rbac.permissions.RBACPermission',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# AI 代码生成配置（需在环境变量中提供 AI_CODEGEN_API_KEY）
AI_CODEGEN = {
    'ENABLED': bool(os.getenv('AI_CODEGEN_API_KEY')),
    'API_KEY': os.getenv('AI_CODEGEN_API_KEY', ''),
    'PROVIDER': os.getenv('AI_CODEGEN_PROVIDER', 'openai'),
    'MODEL': os.getenv('AI_CODEGEN_MODEL', 'gpt-4o-mini'),
    'BASE_URL': os.getenv('AI_CODEGEN_BASE_URL', 'https://api.openai.com/v1'),
    'TEMPERATURE': float(os.getenv('AI_CODEGEN_TEMPERATURE', '0.1')),
    'TIMEOUT': int(os.getenv('AI_CODEGEN_TIMEOUT', '30')),
}

# Channels 配置（WebSocket支持）
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # 开发环境使用内存层，生产环境建议使用Redis
    }
}

# 如果配置了REDIS_URL，使用Redis作为通道层（生产环境推荐）
REDIS_URL = os.getenv('REDIS_URL', '')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }