# Generated by Django 5.2.7 on 2025-11-03 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='名称')),
                ('path', models.CharField(blank=True, default='', max_length=128, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=128, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.menu', verbose_name='父级')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_organizations', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('ANY', 'ANY')], default='ANY', max_length=6, verbose_name='请求方法')),
                ('url_pattern', models.CharField(max_length=256, verbose_name='URL 匹配')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='rbac.menu', verbose_name='所属菜单')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('data_scope', models.CharField(choices=[('ALL', '全部数据'), ('DEPT', '本部门'), ('DEPT_AND_SUB', '本部门及下级'), ('SELF', '仅本人'), ('CUSTOM', '自定义组织')], default='SELF', max_length=16, verbose_name='数据范围')),
                ('custom_data_organizations', models.ManyToManyField(blank=True, related_name='roles_with_custom_scope', to='rbac.organization', verbose_name='自定义数据范围组织')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='rbac.menu', verbose_name='菜单可见')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主组织')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to='rbac.organization', verbose_name='组织')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户组织',
                'verbose_name_plural': '用户组织',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['parent'], name='rbac_menu_parent__543af2_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['order'], name='rbac_menu_order_655075_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent'], name='rbac_organi_parent__84ac6f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['order'], name='rbac_organi_order_5990b9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['code'], name='rbac_organi_code_167236_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='rbac_permis_code_f6107f_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['http_method'], name='rbac_permis_http_me_77b18e_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='rbac_role_code_7dbf08_idx'),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['user'], name='rbac_useror_user_id_9f56c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['organization'], name='rbac_useror_organiz_cb5127_idx'),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['is_primary'], name='rbac_useror_is_prim_39a0d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='rbac_userro_user_id_51c836_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='rbac_userro_role_id_32b7c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
